=head1 NAME

Mojolicious::Plugin::Ident - Mojo plugin to interact with an ident server

=head1 VERSION

version 0.1

=head1 SYNOPSIS

 use Mojolicious::Lite;
 plugin 'ident';
 
 # get the username of the remote using ident protocol
 get '/' => sub {
   my $self = shift;
   $self->render_text("hello " . $self->ident->username);
 };
 
 # only allow access to the user on localhost which 
 # started the mojolicious lite app
 under sub { eval { shift->ident->same_user } };
 
 get '/private' => sub {
   shift->render_text("secret place");
 };

=head1 DESCRIPTION

This is a plugin to easily interact with ident authentication
server running on the remote server.

=head1 OPTIONS

=head2 timeout

Number of seconds to wait before timing out in the connection with the
remote ident server.  The default is 2.

=head1 HELPERS

=head2 ident

Returns an instance of L<Mojolicious::Plugin::Ident::Response>, which
has two fields, username and os.

 get '/' => sub {
   my $self = shift;
   my $ident = $self->ident;
   $self->render_text(
     "username: " . $ident->username .
     "os:       " . $ident->os
   );
 };

It also has a same_user method which can be use to determine if the
user on the server and the remote are the same.  The user is considered
the same if the remote connection came over the loopback address
(127.0.0.1) and the username matches either the server's username or 
real uid.

 under sub { eval { shift->ident->same_user } };
 get '/private' => 'private_route';

Throws an exception if

=over 4

=item * it cannot connect to the remote's ident server

=item * the connection to the remote's ident server times out

=item * the remote ident server returns an error

=back

=head1 AUTHOR

Graham Ollis <plicease@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Graham Ollis.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

